version: '2'

x-logging:
  &default-logging
  logging:
    driver: json-file
    options:
      max-size: 100m

services:
  web:
    build: .
    image: gamification:latest
    command: ['python', 'manage.py', 'runserver', '0.0.0.0:8000']
    ports:
      - "80:8000"

  server-extra:
    image: judge0/api:1.9.0-extra
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    ports:
      - "3000"
    privileged: true
    <<: *default-logging
    restart: always

  workers-extra:
    image: judge0/api:1.9.0-extra
    command: ["./scripts/workers"]
    volumes:
      - ./judge0.conf:/judge0.conf:ro
    privileged: true
    <<: *default-logging
    restart: always

  db:
    image: postgres:9.6
    env_file: judge0.conf
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data/
    privileged: true
    <<: *default-logging
    restart: always

  redis:
    image: redis:4.0
    command: [
      "bash", "-c",
      'docker-entrypoint.sh --appendonly yes --requirepass "$$REDIS_PASSWORD"'
    ]
    env_file: judge0.conf
    ports:
      - "6379:6379"
    volumes:
      - ./srv/redis-data:/data
    <<: *default-logging
    restart: always