# Generated by Django 3.0.14 on 2022-10-22 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('canvas', '0014_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='canvascourse',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
