name: Flake8

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v2
    - uses: psf/black@stable
      with:
        options: "--check"
        src: "."
        version: "22.10.0"
